### ISSUE TITLE
Projeto Figma

### ISSUE THREAD

**Issue by jocimarjsc** [KaianDev/fsw-barbershop#1]
Olá, não consegui acompanhar tudo, pois moro fora do Brasil, e o horária dificulta, por acaso você tem o projeto do figma?

**Comment by KaianDev** [comment]
Olá, boa noite, segue o figma https://www.figma.com/design/Iuu5y8fheemP8HOfFHnAZe/FSW-5.0-%5BLive%5D-(Copy)?node-id=601-8722&t=ocAbPKubdvE3wScN-0

**Comment by jocimarjsc** [comment]
Obrigado
